name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm ci --ignore-scripts
    - name: Build
      run: npx nps build
    - name: Test
      run: |
        npx nps test
        npx codacy-coverage -v < ./coverage/lcov.info
