name: ci
on:
  - push
  - pull_request
env:
  FORCE_COLOR: 3
jobs:
  ci-cd:
    name: CI/CD
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npx nr build

      - name: Test
        run: |
          npx nr test.coverage
          bash <(curl -s https://codecov.io/bash)

      # - name: Release
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: |
      #     npx semantic-release
      #     npx nr publish
