name: ci
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
env:
  FORCE_COLOR: 3
concurrency:
  group: ${{ github.ref_name }}
  # Only cancel concurrent builds when we are not on the default branch. This
  # way, if a commit breaks the default branch, we can more easily determine
  # which commit caused the failure.
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}
jobs:
  ci:
    name: CI
    # Skip building tags; an identical job for the commit to which the tag
    # points will be triggered anyway.
    if: github.ref_type != 'tag'
    runs-on: ubuntu-latest
    steps:

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install Dependencies
        run: npm clean-install

      - name: Build Project
        run: npx nr build

      # - name: Unit Tests
      #   run: npx nr test.coverage

      # - name: Upload Coverage Report
      #   uses: codecov/codecov-action@v3

      # - name: Release
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npx nr release

      # - name: Post-Release / Capture Environment Variables
      #   if: ${{ always() }}
      #   run: |
      #     echo "REPO=${{ github.repository }}" >> $GITHUB_ENV
      #     echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
      #     echo "RUN_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      # - name: Post-Release / Send Success Notification
      #   if: ${{ success() }}
      #   run: |
      #     curl --silent \
      #     --data-urlencode "user=${{ secrets.PUSHOVER_USER }}" \
      #     --data-urlencode "token=${{ secrets.PUSHOVER_TOKEN }}" \
      #     --data-urlencode "title=🚀 Workflow Run Succeeded" \
      #     --data-urlencode "html=1" \
      #     --data-urlencode "message=$REPO $VERSION" \
      #     --data-urlencode "url_title=View Workflow Run" \
      #     --data-urlencode "url=$RUN_URL" \
      #     --data-urlencode "sound=confirmation" \
      #     https://api.pushover.net/1/messages.json

      # - name: Post-Release / Send Error Notification
      #   if: ${{ failure() }}
      #   run: |
      #     curl --silent \
      #     --data-urlencode "user=${{ secrets.PUSHOVER_USER }}" \
      #     --data-urlencode "token=${{ secrets.PUSHOVER_TOKEN }}" \
      #     --data-urlencode "title=❗️ Workflow Run Failed" \
      #     --data-urlencode "html=1" \
      #     --data-urlencode "message=$REPO" \
      #     --data-urlencode "url_title=View Workflow Run" \
      #     --data-urlencode "url=$RUN_URL" \
      #     --data-urlencode "sound=kill-bill-siren" \
      #     https://api.pushover.net/1/messages.json
